name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Test minimum'
        id: schema
        uses: ./
        with:
          schema: '__tests__/schema.json'
      - run: |
          test -f "${{ steps.schema.outputs.path }}"
        shell: bash
      - name: 'Test output path'
        uses: ./
        with:
          schema: '__tests__/schema.json'
          output: '__tests__/schema.graphql'
      - run: |
          test -f "__tests__/schema.graphql"
        shell: bash